<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MediaGeneralSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $planMediaGeneral = [
            'IDPlanEstudio' => 1,
            'nombre' => 'Media General',
            'codigo' => 'MG-2020',
            'descripcion' => 'Plan de estudios para la media general',
            'activo' => true,
            'fechaCreado' => now(),
            'fechaModificado' => now(),
        ];
        $componentesMediaGeneral = [
            [
                'IDComponente' => 1,
                'nombre' => '1er Año',
                'descripcion' => 'Primer año de la media general',
                'planEstudioID' => 1,
                'prelaID' => null,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDComponente' => 2,
                'nombre' => '2do Año',
                'descripcion' => 'Segundo año de la media general',
                'planEstudioID' => 1,
                'prelaID' => 1,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDComponente' => 3,
                'nombre' => '3er Año',
                'descripcion' => 'Tercer año de la media general',
                'planEstudioID' => 1,
                'prelaID' => 2,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDComponente' => 4,
                'nombre' => '4to Año',
                'descripcion' => 'Cuarto año de la media general',
                'planEstudioID' => 1,
                'prelaID' => 3,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDComponente' => 5,
                'nombre' => '5to Año',
                'descripcion' => 'Quinto año de la media general',
                'planEstudioID' => 1,
                'prelaID' => 4,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
        ];
        $materiasMediaGeneral = [
            [
                'IDMateria' => 1,
                'nombre' => 'Castellano',
                'descripcion' => 'Castellano para el primer año',
                'componenteID' => 1,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 2,
                'nombre' => 'Inglés y otras Lenguas Extranjeras',
                'descripcion' => 'Inglés y otras Lenguas Extranjeras para el primer año',
                'componenteID' => 1,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 3,
                'nombre' => 'Matemáticas',
                'descripcion' => 'Matemáticas para el primer año',
                'componenteID' => 1,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 4,
                'nombre' => 'Educación Física',
                'descripcion' => 'Educación Física para el primer año',
                'componenteID' => 1,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 5,
                'nombre' => 'Arte y Patrimonio',
                'descripcion' => 'Arte y Patrimonio para el primer año',
                'componenteID' => 1,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 6,
                'nombre' => 'Ciencias Naturales',
                'descripcion' => 'Ciencias Naturales para el primer año',
                'componenteID' => 1,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 7,
                'nombre' => 'Geografía, Historia y Ciudadanía',
                'descripcion' => 'Geografía, Historia y Ciudadanía para el primer año',
                'componenteID' => 1,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 8,
                'nombre' => 'Castellano',
                'descripcion' => 'Castellano para el segundo año',
                'componenteID' => 2,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 9,
                'nombre' => 'Inglés y otras Lenguas Extranjeras',
                'descripcion' => 'Inglés y otras Lenguas Extranjeras para el segundo año',
                'componenteID' => 2,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 10,
                'nombre' => 'Matemáticas',
                'descripcion' => 'Matemáticas para el segundo año',
                'componenteID' => 2,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 11,
                'nombre' => 'Educación Física',
                'descripcion' => 'Educación Física para el segundo año',
                'componenteID' => 2,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 12,
                'nombre' => 'Arte y Patrimonio',
                'descripcion' => 'Arte y Patrimonio para el segundo año',
                'componenteID' => 2,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 13,
                'nombre' => 'Ciencias Naturales',
                'descripcion' => 'Ciencias Naturales para el segundo año',
                'componenteID' => 2,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 14,
                'nombre' => 'Geografía, Historia y Ciudadanía',
                'descripcion' => 'Geografía, Historia y Ciudadanía para el segundo año',
                'componenteID' => 2,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 15,
                'nombre' => 'Castellano',
                'descripcion' => 'Castellano para el tercer año',
                'componenteID' => 3,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 16,
                'nombre' => 'Inglés y otras Lenguas Extranjeras',
                'descripcion' => 'Inglés y otras Lenguas Extranjeras para el tercer año',
                'componenteID' => 3,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 17,
                'nombre' => 'Matemáticas',
                'descripcion' => 'Matemáticas para el tercer año',
                'componenteID' => 3,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
             [
                'IDMateria' => 18,
                'nombre' => 'Física',
                'descripcion' => 'Física para el tercer año',
                'componenteID' => 3,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 19,
                'nombre' => 'Química',
                'descripcion' => 'Química para el tercer año',
                'componenteID' => 3,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 20,
                'nombre' => 'Biología',
                'descripcion' => 'Biología para el tercer año',
                'componenteID' => 3,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 21,
                'nombre' => 'Geografía, Historia y Ciudadanía',
                'descripcion' => 'Geografía, Historia y Ciudadanía para el tercer año',
                'componenteID' => 3,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 22,
                'nombre' => 'Castellano',
                'descripcion' => 'Castellano para el cuarto año',
                'componenteID' => 4,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 23,
                'nombre' => 'Inglés y otras Lenguas Extranjeras',
                'descripcion' => 'Inglés y otras Lenguas Extranjeras para el cuarto año',
                'componenteID' => 4,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 24,
                'nombre' => 'Matemáticas',
                'descripcion' => 'Matemáticas para el cuarto año',
                'componenteID' => 4,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 25,
                'nombre' => 'Física',
                'descripcion' => 'Física para el cuarto año',
                'componenteID' => 4,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 26,
                'nombre' => 'Química',
                'descripcion' => 'Química para el cuarto año',
                'componenteID' => 4,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 27,
                'nombre' => 'Biología',
                'descripcion' => 'Biología para el cuarto año',
                'componenteID' => 4,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 28,
                'nombre' => 'Geografía, Historia y Ciudadanía',
                'descripcion' => 'Geografía, Historia y Ciudadanía para el cuarto año',
                'componenteID' => 4,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 29,
                'nombre' => 'Formación para la Soberanía Nacional',
                'descripcion' => 'Formación para la Soberanía Nacional para el cuarto año',
                'componenteID' => 4,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 30,
                'nombre' => 'Castellano',
                'descripcion' => 'Castellano para el quinto año',
                'componenteID' => 5,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 31,
                'nombre' => 'Inglés y otras Lenguas Extranjeras',
                'descripcion' => 'Inglés y otras Lenguas Extranjeras para el quinto año',
                'componenteID' => 5,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 32,
                'nombre' => 'Matemáticas',
                'descripcion' => 'Matemáticas para el quinto año',
                'componenteID' => 5,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                 'IDMateria' => 33,
                'nombre' => 'Física',
                'descripcion' => 'Física para el quinto año',
                'componenteID' => 5,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 34,
                'nombre' => 'Química',
                'descripcion' => 'Química para el quinto año',
                'componenteID' => 5,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 35,
                'nombre' => 'Biología',
                'descripcion' => 'Biología para el quinto año',
                'componenteID' => 5,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 36,
                'nombre' => 'Geografía, Historia y Ciudadanía',
                'descripcion' => 'Geografía, Historia y Ciudadanía para el quinto año',
                'componenteID' => 5,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
            [
                'IDMateria' => 37,
                'nombre' => 'Formación para la Soberanía Nacional',
                'descripcion' => 'Formación para la Soberanía Nacional para el quinto año',
                'componenteID' => 5,
                'cualitativa' => false,
                'calcular' => true,
                'fechaCreado' => now(),
                'fechaModificado' => now(),
            ],
        ];
        DB::transaction(function () use ($planMediaGeneral, $componentesMediaGeneral, $materiasMediaGeneral) {
            DB::table('PlanesDeEstudios')->insert($planMediaGeneral);
            DB::table('Componentes')->insert($componentesMediaGeneral);
            DB::table('Materias')->insert($materiasMediaGeneral);
        });
    }
}
